# Generated by Django 4.2.7 on 2023-11-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cost_center',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='integration_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
