# Generated by Django 4.2.7 on 2023-11-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('departments', '0002_alter_department_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'company')},
        ),
    ]
