# Generated by Django 4.2.7 on 2023-11-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
